# GNU Makefile for libraries
#
# Please compile with GNU make.
#
# 2005 bl0rg.net

all: libs

libs: libfec.so

CFLAGS += -Wall -O2 -fPIC

# Create dependencies
%.d: %.c
	$(CC) -MM $(CFLAGS) $< > $@
	$(CC) -MM $(CFLAGS) $< | sed s/\\.o/.d/ >> $@

MP3_OBJS     := mp3-read.o mp3-write.o mp3.o aq.o id3.o
UTILS_OBJS   := pack.o bv.o signal.o dlist.o file.o buf.o crc32.o
FEC_OBJS     := galois.o matrix.o fec.o fec-pkt.o fec-rb.o fec-group.o

OBJS := $(MP3_OBJS) \
        $(OGG_OBJS) \
        $(NETWORK_OBJS) \
        $(RTP_OBJS) \
        $(UTILS_OBJS) \
        $(FEC_OBJS)
DEPS := $(patsubst %.o,%.d,$(OBJS))
include $(DEPS)

# FEC library
LIBFEC_OBJS := $(UTILS_OBJS) $(MP3_OBJS) $(FEC_OBJS) libfec.o
include libfec.d

libfec.a: $(LIBFEC_OBJS)
	ar r $@ $(LIBFEC_OBJS)

libfec.so: $(LIBFEC_OBJS)
	$(LD) -o $@ -shared $(LIBFEC_OBJS)
#	$(CC) -dynamiclib -o $@ $(LIBFEC_OBJS)

