.TH MP3LENGTH 1 "February 2005" "" "User Command"
.SH NAME
.B mp3length
\- show the length of a MP3 file
.SH SYNOPSIS
.B mp3length
.I mp3file
.br
.SH DESCRIPTION
.B mp3length
prints the length of a MP3 file in a human readable format. The length
is calculated by counting the ADUs in the MP3 file. The primary goal of this
program was to assist development of 
.B mp3cue
and
.B mp3cut.

.SH AUTHORS
Manuel Odendahl <manuel@bl0rg.net>, Florian Wesch <dividuum@bl0rg.net>

