.TH POC\-3119 1 "February 2005" "" "User Command"
.SH NAME
.B poc\-3119
\- send RTP RFC 3119 MP3 streams 
.SH SYNOPSIS
.B poc\-3119
.RB [
.I \-s address
.RB ]
.RB [
.I \-p port
.RB ]
.RB [
.I \-t ttl
.RB ]
.RB [
.I \-q
.RB ]
.I files...
.SH DESCRIPTION
.B poc\-3119
is a streaming server sending mp3 data using the RTP RFC 3119
protocol. It sends the
.I files
in the order given on the command-line. Use the filename 
.I \-
to stream from standard input. Normally, RTP is used to stream to
multicast groups.
.SH OPTIONS
.IP "-s address"
Specify the address to send to (default 224.0.1.23). 
.IP "-p port"
Specify the port to send to.
.IP "-t ttl"
Specify the TTL parameter to be set on outgoing parameters (default 1).
.IP "-q"
Don't output any information on standard error.
.SH EXAMPLES
.IP "poc-3119 -s 224.0.1.24 -p 8989 -t 2 bla.mp3"
Send the file 
.I bla.mp3
using the RTP RFC 3119 protocol to the address 224.0.1.24 on port
8989, and set the TTL to 2.
.SH AUTHORS
Manuel Odendahl <manuel@bl0rg.net>, Florian Wesch <dividuum@bl0rg.net>



